name: Python application

on:
  schedule:
    - cron: "0 0 * * 3"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout actions
    - uses: actions/checkout@v1

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
		
    - name: Run main.py
      run: |
        pip install --upgrade pip
        pip install pandas numpy pyecharts akshare
        python main.py
		
    - name: commit
      run: |
        git config --global user.email gishusheng@gmail.com
        git config --global user.name xunhs-gh-workflow
        git add .
        git commit -m "update" -a
		
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.personal_token }}
