# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Auto Stock Python Action

on:
  schedule:
    - cron: "30 6 * * 0"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy pyecharts akshare-1.12.62 yfinance
    - name: Run main.py
      run: |
        mkdir public
        mkdir public/html
        mkdir public/data
        mkdir public/dist
        cp autoc.min.css ./public/dist/
        cp autoc.min.js ./public/dist/
        cp bootstrap.min.css ./public/dist/
        cp bootstrap.min.js ./public/dist/
        python main.py
        
    - name: Commit & Push
      run: |

        remote_addr=`git remote get-url --push origin`
        echo "remote addr: ${remote_addr}"
        cd public
        user_name=`git log -1 --pretty=format:'%an'`
        user_email=`git log -1 --pretty=format:'%ae'`
        git config --global init.defaultBranch master
        git init
        git config user.name ${user_name}
        git config user.email ${user_email}
        git add -A
        msg='来自github action的自动部署'
        git commit -m "${msg}"
        remote_addr=`echo $remote_addr|  awk -F'://' '{print $2}'`
        remote_addr=https://${user_name}:${{ secrets.GITHUB_TOKEN }}@${remote_addr}
        git remote add origin ${remote_addr}
        git push origin HEAD:public --force





        
