# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron: "0 0 * * 3"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy pyecharts akshare
    - name: Run main.py
      run: |
        mkdir public
        python main.py
        
    - name: Commit & Push
      run: |
        msg='来自github action的自动部署'
        githubUrl=https://xunhs:${GITHUB_TOKEN}@github.com/xunhs/auto_stock.git
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add -A
        git commit -m "${msg}"
        git push -f $githubUrl main:public
        

        
